name: Env Workflow
on:
  push:
    branches:
      - main
      - muck-with-env
  workflow_dispatch:

jobs:
  prod_job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug
        run: |
          python src/test.py
