name: Test Workflow
on:
  push:
  workflow_dispatch:

jobs:
  test_job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug
        run: |
          python src/test.py
